[project]
name = "hiivelabs-com-python-tools"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "atproto>=0.0.63",
    "beautifulsoup4>=4.14.2",
    "markdown>=3.9",
    "pillow>=11.3.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "requests>=2.32.5",
]
