# main page logo
main:
  logo:
    dark: "/src/assets/images/hiivelabs.com/logos/hiive-logo-dark.svg"
    light: "/src/assets/images/hiivelabs.com/logos/hiive-logo-light.svg"
    alt: "hiivelabs.com"

# navbar setup
navbar:
    # navbar logo setup
    logo:
      dark: "/src/assets/images/hiivelabs.com/logos/hiivelabs-dot-com-dark.svg"
      light: "/src/assets/images/hiivelabs.com/logos/hiivelabs-dot-com-light.svg"
      alt: "hiivelabs.com"

    left:
      -
        code: blog
        href: "/blog"
        label: "blog"
      -
        code: categories
        href: "/categories"
        label: "categories"
      -
        code: tags
        href: "/tags"
        label: "tags"
    right:
      -
        code: mission
        href: "/mission"
        label: "mission statement"
      -
        code: 'about'
        href: '/about'
        label: 'About'
      -
        code: contact
        href: "/contact-us"
        label: "contact us"
    valid_breadcrumbs:
      - "[slug]"
#      - "[...page]"
      - "archive"

# blog path (can be posts or blog)
# posts = src/assets/posts/...
# blog = src/assets/blog/...
blog:
  pagination_size: 5
  path: posts
  prefix: blog/

# footer setup
footer:
    content:
        - "hiivelabs and its logo are registered trademarks of hiive."
        - "All content Â© 2005-[CURRENT_YEAR] by hiive."

# include bluesky
bluesky:
    include: false
    hashtag_link: /categories/#[HASHTAG]

# tag/category information
tags_and_categories:
    aliases:
        machine-learning:
            - ml
        artificial-intelligence:
            - ai
        large-language-model:
            - llm
        reinforcement-learning:
            - rl
